<img src="logo.png">

# Gestión de arrays

## Arreglos especiales

Numpy cuenta con un cierto compendio para matrices. Es importante comentar que, aunque los ejemplos siguientes son para matrices, se adaptan fácilmente indicando el shape para aplicarse a cualquier tipo de arreglo. Además, toma en cuenta el parámetro *dtype* que nos indica que el tipo de dato a considerar, el cual, usualmente, es de tipo flotante:

``np.función(shape,dtype)``

donde 

``shape`` es una tupla donde se indica la forma del arreglo y

``dtype`` es el tipo de dato con que queremos llenarla.

In [1]:
import numpy as np

In [2]:
# Matriz donde todos los elementos son iguales a 1: np.ones((u,v))

np.ones([2,1])

array([[1.],
       [1.]])

In [3]:
np.ones((4,3),dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [4]:
# Matriz donde todos los elementos son iguales a 0: np.zeros((u,v))

np.zeros((2,1))

array([[0.],
       [0.]])

In [5]:
np.zeros((4,3),dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
# Matriz donde todos sus elementos son vacíos: np.empty((u,v))

np.empty((2,1),dtype = str)

array([[''],
       ['']], dtype='<U1')

In [15]:
np.empty([4,3],dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### La función np.arange().

La función np.arange() generará un arreglo de una dimensión que contiene los enteros definidos en un rango al estilo de range().

``np.arange(inicio, fin, incrementos, dtype=<tipo de dato>)``

donde 

* ``<inicio>`` corresponde al número a partir del cual comenzará la secuencia.
* ``<fin>`` corresponde al número en el que terminará la secuencia
* ``<incrementos>`` correpsonde al número unidades que se incrementarán sucesivamente desde el valor inicial hasta uno antes del valor final.
* ``<tipo de dato>`` es el tipo de dato que tendrá el arreglo.


El valor por defecto del valor inicial es 0.

El valor por defecto de los incrementos es de 1.

Si no se define el valor de dtype, se inferirá el tipo de dato del que se trata.

In [19]:
# Arreglo de una dimensión al estilo de un range: np.arange(<inicio>,<final>,incrementos,dtype)

#np.arange(5,12)
print(np.arange(5,12))
list(range(5,12))

[ 5  6  7  8  9 10 11]


[5, 6, 7, 8, 9, 10, 11]

In [20]:
np.arange(6.24, 15.2, 0.8)

array([ 6.24,  7.04,  7.84,  8.64,  9.44, 10.24, 11.04, 11.84, 12.64,
       13.44, 14.24, 15.04])

### La función np.linspace().

Esta función creará un arreglo de una dimensión que contiene una secuencia lineal de números dentro de un rango dado entre un valor incial y un valor final. El número de segmentos incluyendo el valor incial y el valor final es definido meduante el parámentro num. El valor por defecto del parámetro num es de 50.

``np.linspace(inicio, fin, num=segmentos, dtype=tipo de dato)``

Donde:

* ``inicio`` corresponde al número a partir del cual comenzará la secuencia.
* ``fin`` corresponde al número en el que terminará la secuencia
* ``segmentos`` correpsonde al número de segmentos, incluyendo el valor inicial y el final que se generarán, que contendrá el arreglo.
* ``tipo de dato`` es el tipo de dato que tendrá el arreglo.

El valor por defecto del parámetro dtype es np.float.

**Nota:** una partición del intervalo $[a,b]$ (es decir, los números mayores o iguales a $a$ y menores o iguales a $b$)  de tamaño $n$ es una conjunto (en el sentido matemático) de la forma $\{x_1,x_2,...,x_n\}$ donde $$x_1=a<x_2<x_3<...<x_{n-1}<x_n=b$$

Si además $x_2-x_1=x_3-x_2=x_4-x_3=...=x_n-x_{n-1}$, se dice que es una partición equidistante.

In [28]:
np.linspace(20,25,100)

array([20.        , 20.05050505, 20.1010101 , 20.15151515, 20.2020202 ,
       20.25252525, 20.3030303 , 20.35353535, 20.4040404 , 20.45454545,
       20.50505051, 20.55555556, 20.60606061, 20.65656566, 20.70707071,
       20.75757576, 20.80808081, 20.85858586, 20.90909091, 20.95959596,
       21.01010101, 21.06060606, 21.11111111, 21.16161616, 21.21212121,
       21.26262626, 21.31313131, 21.36363636, 21.41414141, 21.46464646,
       21.51515152, 21.56565657, 21.61616162, 21.66666667, 21.71717172,
       21.76767677, 21.81818182, 21.86868687, 21.91919192, 21.96969697,
       22.02020202, 22.07070707, 22.12121212, 22.17171717, 22.22222222,
       22.27272727, 22.32323232, 22.37373737, 22.42424242, 22.47474747,
       22.52525253, 22.57575758, 22.62626263, 22.67676768, 22.72727273,
       22.77777778, 22.82828283, 22.87878788, 22.92929293, 22.97979798,
       23.03030303, 23.08080808, 23.13131313, 23.18181818, 23.23232323,
       23.28282828, 23.33333333, 23.38383838, 23.43434343, 23.48

In [31]:
np.linspace(0,np.pi,num=100).shape


(100,)

## Modificación de la forma y tamaño de un arreglo.

Estudiaremos cuatro formas básicas para manipular los tamaños de un arreglo:

* np.ravel()
* np.reshape()
* np.resize()
* np.concatenate()



### La función np.ravel()

La función *np.ravel()* regresará un arreglo de una dimensión que contiene la referencia de cada uno de los elementos del arreglo que se ingresa como argumento.

``np.ravel(<arreglo>)``

Donde ``<arreglo>`` es un arreglo de Numpy.

In [32]:
arreglo_1 = np.array([[1, 2, 3],
                      [4, 0, -5],
                      [-6, -7, -8]])

np.ravel(arreglo_1)

array([ 1,  2,  3,  4,  0, -5, -6, -7, -8])

In [33]:
arreglo_1

array([[ 1,  2,  3],
       [ 4,  0, -5],
       [-6, -7, -8]])

### La función np.reshape().

La función *np.reshape()* regresará un arreglo compuesto por el mismo número de elementos que el arreglo ingresado como primer argumento, pero con la forma descrita por el objeto de tipo tuple que se ingrese como segundo argumento. Las nuevas dimensiones deben de coincidir con el numero total de elementos del arreglo de origen.

``np.reshape(<arreglo>, <forma>)``

Donde:

* ``<arreglo>`` es un arreglo de Numpy.
* ``<forma>`` es un un objeto de tipo tuple que describe la forma del arreglo resultante.

In [34]:
arreglo_2 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

arreglo_2.shape

(3, 4)

In [38]:
np.reshape(arreglo_2,(6, 2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [42]:
np.arange(1,21)

np.reshape(np.arange(1,21),(10,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

### La función np.resize()

La función *np.resize()* regresará un nuevo arreglo a partir del arreglo que se ingrese como primer argumento, con la forma que se ingrese como segundo argumento.

En caso de que las nuevas dimensiones sean menores a tamaño original, se recortarán los últimos de ellos.

En caso de que las nuevas dimensiones sean mayores al tamaño original, los elementos faltantes serán sustituidos por una secuencia iterativa de los elementos contenidos en el arreglo.

``np.resize(<arreglo>, <forma>)``

Donde:

* ``<arreglo>`` es un arreglo de Numpy.
* ``<forma>`` es un objeto de tipo tuple que describe la nueva forma del arreglo resultante.

In [44]:
arreglo_3 = np.array([[1, 2],
                     [3, 4]])
print(arreglo_3)

[[1 2]
 [3 4]]


In [48]:
arreglo_3

array([[1, 2],
       [3, 4]])

In [50]:
np.resize(arreglo_3, (3, 3))  # Aplica un ravel y queda [1 2 3 4]


array([[1, 2, 3],
       [4, 1, 2],
       [3, 4, 1]])

### La función np.concatenate().

Une una secuencia de arreglos contenidos dentro de un objeto tuple a un eje existente, se puede indicar el eje en el que se realizará la operación ingresando su número correspondiente como tercer argumento.

``np.concatenate(<arreglo 1>, <arreglo 2>, <eje>)``

Donde 

* ``eje = 0`` significa pegar arreglo 2 debajo de arreglo 1
* ``eje = 1`` significa pegar arreglo 2 a la derecha de arreglo 1


In [51]:
arreglo_1 = np.array([[1, 2],
                      [3, 4]])

arreglo_2 = np.array([[5, 6],
                      [7, 8]])

In [53]:
np.concatenate((arreglo_1, arreglo_2), 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## Matrices con elementos aleatorios

### El paquete np.random.

#### La función np.random.rand().

La función *np.random.rand()* crea un arreglo cuyos elementos son valores aleatorios que van de 0 a antes de 1 dentro de una distribución uniforme.

``np.random.rand(<forma>)``

Donde ``forma`` es una secuencia de valores enteros separados por comas que definen la forma del arreglo.



In [60]:
#La siguiente celda generará un arreglo de forma (3,5) conteniendo números aleatorios.

np.random.uniform(1,2,(3,5))

array([[1.74725598, 1.48844252, 1.17754258, 1.76968055, 1.43679406],
       [1.54717913, 1.3173269 , 1.37628416, 1.62134911, 1.43300791],
       [1.8869298 , 1.9433306 , 1.73322261, 1.66533703, 1.52219277]])

#### La función np.random.randint().

La función *np.random.randint()* crea un arreglo cuyos elementos son valores entros aleatorios en un rango dado.

``np.random.randint(<inicio>, <fin>, <forma>)``

Donde:

``<inicio>`` es el valor inicial del rango a partir del cual se generarán los números aleatorios, incluyéndolo a este.

``<fin>`` es el valor final del rango a partir del cual se generarán los números aleatorios, sin incluirlo.

``<forma>`` es un objeto tuple que definen la forma del arreglo.

In [61]:
# La siguente celda creará una arreglo de forma (3, 3) con valores enteros que pueden ir de 1 a 2.

np.random.randint(1, 3, (3, 3))

array([[2, 2, 1],
       [2, 1, 1],
       [2, 1, 1]])

In [62]:
# La siguente celda creará una arreglo de  con valores enteros que pueden ir de 0 a 255.

np.random.randint(0, 256, (10, 3))

array([[ 49, 127,   1],
       [141,  79, 113],
       [ 20, 165,  17],
       [249,  89, 142],
       [ 83,  18, 120],
       [195,  62, 229],
       [ 70, 171, 212],
       [204,  81,  94],
       [155, 243,  17],
       [196, 235,  29]])

## Álgebra lineal
    
El componente más poderoso de Numpy es su capacidad de realizar operaciones con arreglos, y un caso particular de ellos sobn las matrices numéricas.    



### Matriz identidad

Se refiere a matrices cuadradas donde todos los elementos son cero excepto aquellos de la diagonal principal, que valen 1.

In [64]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Producto puntual (de Hadamard) de dos matrices.

Es el producto "elemento a elemento" de dos matrices. Ambas deben ser del mismo tamaño.



In [66]:
# matriz1 * matriz2
print(np.array([[1,2,3],[4,5,6]]))
print(np.array([[0,1,0],[0,0,1]]))


[[1 2 3]
 [4 5 6]]
[[0 1 0]
 [0 0 1]]


In [67]:
np.array([[1,2,3],[4,5,6]]) * np.array([[0,1,0],[0,0,1]])

array([[0, 2, 0],
       [0, 0, 6]])

In [68]:
A = np.array([[1,4,3],[2,5,1]])

(A >= 3 ) * A

array([[0, 4, 3],
       [0, 5, 0]])

In [69]:
A >= 3

array([[False,  True,  True],
       [False,  True, False]])

### Producto usual de matrices

Es el producto usual de matrices. Se debe tomar en cuenta que si $A$ y $B$ son dos matrices, para que el producto $AB$ tenga sentido se debe cumplir que el número de columnas de $A$ es igual al número de filas de $B$. Se obtiene como resultado una matriz con el mismo número de filas que $A$ y el mismo número de columnas de $B$

In [76]:
A = np.array([[1,4,3],[2,5,1]])
B = np.array([[2,3,1,0],[5,5,1,0],[4,1,2,0]])
print(f"las matrices son A=\n{A} y B=\n{B}")


las matrices son A=
[[1 4 3]
 [2 5 1]] y B=
[[2 3 1 0]
 [5 5 1 0]
 [4 1 2 0]]


Las matrices de este ejemplo son $$\left(\begin{array}{ccc}1&4&3\\2&5&1\end{array}\right),\left(\begin{array}{cccc}2&3&1&0\\5&5&1&0\\4&1&2&0\end{array}\right)$$

In [78]:
#A @ B

np.dot(A,B)

array([[34, 26, 11,  0],
       [33, 32,  9,  0]])

In [79]:
print(f"La forma de A es {A.shape}; la de B es {B.shape}. Por lo tanto la de AB es {(A @ B).shape}")

La forma de A es (2, 3); la de B es (3, 4). Por lo tanto la de AB es (2, 4)


### El paquete numpy.linalg

La biblioteca especializada en operaciones de algebra lineal de Numpy es numpy.linalg.

Algunas de las funciones mas importantes que contiene son

* np.linalg.det()
* np.linalg.solve()
* np.linalg.inv()

#### Determinantes

Considere la matriz $$\left(\begin{array}{ccc}0&1&2\\3&4&5\\6&7&8\end{array}\right)$$

In [82]:
# El cálculo de su determinante es 0+42+30-48-0-24

A = np.arange(9).reshape(3,3)

np.linalg.det(A)



0.0

### Soluciones de ecuaciones lineales con la función ```np.linalg.solve()```.

Un sistema de ecuaciones lineales coresponde un conjunto de ecuaciones de la forma:

$$
a_{11}x_1 + a_{12}x_2 + \cdots a_{1n}x_n = y_1 \\
a_{21}x_1 + a_{22}x_2 + \cdots a_{2n}x_n = y_2\\
\vdots\\
a_{m1}x_1 + a_{m2}x_2 + \cdots a_{mn}x_n = y_m
$$

Lo cual puede ser expresado de forma matricial.

$$ 
\begin{bmatrix}a_{11}\\a_{21}\\ \vdots\\ a_{m1}\end{bmatrix}x_1 + \begin{bmatrix}a_{12}\\a_{22}\\ \vdots\\ a_{m2}\end{bmatrix}x_2 + \cdots \begin{bmatrix}a_{m1}\\a_{m2}\\ \vdots\\ a_{mn}\end{bmatrix}x_n = \begin{bmatrix}y_{1}\\y_{2}\\ \vdots\\ y_{m}\end{bmatrix}
$$

Existen múltiples métodos para calcular los valores $x_1, x_2 \cdots x_n$ que cumplan con el sistema siempre que $m = n$.

Numpy cuenta con la función *np.linalg.solve()*, la cual puede calcular la solución de un sistema de ecuaciones lineales al expresarse como un par de matrices de la siguiente foma:

$$ 
\begin{bmatrix}a_{11}&a_{12}&\cdots&a_{1n}\\a_{21}&a_{22}&\cdots&a_{2n}\\ \vdots\\ a_{n1}&a_{n2}&\cdots&a_{nn}\end{bmatrix}= \begin{bmatrix}y_{1}\\y_{2}\\ \vdots\\ y_{n}\end{bmatrix}
$$

La función ```numpy.linagl.solve()``` permite resolver sistemas de ecuaciones lineales ingresando un arreglo de dimensiones ```(n, n)``` como primer argumente y otro con dimensión ```(n)``` como segundo argumento. 

**Ejemplo:**

* Para resolver el sistema de ecuaciones:

$$
2x_1 + 5x_2 - 3x_3 = 22.2 \\
11x_1 - 4x_2 + 22x_3 = 11.6 \\
54x_1 + 1x_2 + 19x_3 = -40.1 \\
$$

* Se realiza lo siguiente:

In [83]:
a = np.array([[2, 5, -3],
              [11, -4, 22],
              [54, 1, 19]])

y = np.array([22.2, 11.6, -40.1])

np.linalg.solve(a, y)

array([-1.80243902,  6.7549776 ,  2.65666999])

## Matriz inversa.

In [84]:
np.linalg.inv(a)

array([[-0.02439024, -0.02439024,  0.02439024],
       [ 0.24365356,  0.04977601, -0.01916376],
       [ 0.05649577,  0.06669985, -0.01567944]])

In [95]:
np.round(np.linalg.inv(a) @ a ,3)

array([[ 1.,  0., -0.],
       [ 0.,  1.,  0.],
       [-0., -0.,  1.]])

In [86]:
np.linalg.inv(a).dot(y)  # Ax=y y por lo tanto x=A^{-1}y

array([-1.80243902,  6.7549776 ,  2.65666999])

## Transpuesta de una matriz

In [87]:
b = np.arange(9).reshape((3,3))
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [88]:
b.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [89]:
np.transpose(b)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])